name: Xcode - Build and Analyze

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install name tool
        run: |
          xcrun vtool -arch arm64 -set-build-version 10.2 10.2 -replace -output ./minecraftappletv.hi.arm64 ./minecraftappletv.hi.arm64
          xcrun vtool -arch arm64 -show ./minecraftappletv.hi.arm64
        #run: |
          #install_name_tool -add_rpath @executable_path/Frameworks ./hook.dylib
          #install_name_tool -change /System/Library/Frameworks/OpenGLES.framework/OpenGLES @rpath/ANGLEGLKit.framework/ANGLEGLKit ./hook.dylib
          #install_name_tool -add_rpath @executable_path/Frameworks ./GeometryJump
          #install_name_tool -change /System/Library/Frameworks/OpenGLES.framework/OpenGLES @rpath/ANGLEGLKit.framework/ANGLEGLKit ./GeometryJump
      - uses: actions/upload-artifact@v4
        with:
            path: | 
                ./
