name: Xcode - Build and Analyze

on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: install name tool
        #run: |
          #mkdir ./Xcode.app/
          #mkdir ./Xcode.app/hi
          #ls ../../../../../Applications/
          #cp -R ../../../../../Applications/XCode_16.1_beta_2.app/ ./Xcode.app/hi
          #rm -rf ./Xcode.app/hi/Contents/Developer/Platforms/MacOSX.platform
          #rm -rf ./Xcode.app/hi/Contents/Applications/Instruments.app
          #zip -r ./hello.zip ./
          #gh release upload xcodereal ./hello.zip
        run: |
          brew install ldid
          xcrun vtool -arch arm64 -set-build-version 2 8.0 10.2 -replace -output "./Image Playground" "./Image Playground"
          xcrun vtool -arch arm64 -show "./Image Playground"
          ldid -e "./Image Playground" > ent.xml
        #run: |
          
          #install_name_tool -add_rpath @executable_path/Frameworks ./GeometryJump
          #install_name_tool -change /System/Library/Frameworks/OpenGLES.framework/OpenGLES @rpath/ANGLEGLKit.framework/ANGLEGLKit ./GeometryJump        
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
            path: |
                ./
