name: Xcode - Build and Analyze

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install name tool
        run: |
          mkdir ./Xcode.app/
          mkdir ./Xcode.app/hi
          ls ../../../../../Applications/
          cp -R ../../../../../Applications/XCode_16.1_beta_2.app/ ./Xcode.app/hi
          zip -r ./hello.zip ./Xcode.app/
        #run: |
          #xcrun vtool -arch arm64 -set-build-version 2 8.0 10.2 -replace -output ./minecraftappletv ./minecraftappletv
          #xcrun vtool -arch arm64 -show ./minecraftappletv
          #xcrun vtool -arch arm64 -set-build-version 2 8.0 10.2 -replace -output ./XSAPITCUI.framework/XSAPITCUI ./XSAPITCUI.framework/XSAPITCUI
          #xcrun vtool -arch arm64 -show ./XSAPITCUI.framework/XSAPITCUI
        #run: |
          
          #install_name_tool -add_rpath @executable_path/Frameworks ./GeometryJump
          #install_name_tool -change /System/Library/Frameworks/OpenGLES.framework/OpenGLES @rpath/ANGLEGLKit.framework/ANGLEGLKit ./GeometryJump
      - uses: actions/upload-artifact@v4
        with:
            path: | 
                ./hello.zip
